# Tomcat端口号
server:
  port: 8081
  # 数据源配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    password: 123456
    username: root
  redis:
    # Redis数据库索引 (0-15) 默认为0
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis连接端口
    port: 6379
    # Redis连接密码(默认为空)
    password:
    # 连接超时时间（毫秒）
    timeout: 5000ms
    jedis:
      pool:
        # Redis最大连接数(负数表示没有限制) 默认8
        max-active: 8
        # 连接池最大阻塞等待时间（毫秒）（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接 默认8
        max-idle: 8
        # 连接池中的最小空闲连接 默认0
        min-idle: 0
  # mybatis配置
mybatis:
  type-aliases-package: com.example.mybatisredis.domain
  mapper-locations: classpath:mapper/*.xml
# redis 配置
