# master 数据源配置
master:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    password: 123456
    username: root
  #  新的驱动程序类是`com.mysql.cj.jdbc.Driver'。 驱动程序通过SPI自动注册，通常不需要手动加载驱动程序类。
  #    driver-class-name: com.mysql.jdbc.Driver
cluster:
  datasource:
    url: jdbc:mysql://localhost:3306/springbootdb?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    password: 123456
    username: root
  #    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8081
  #  mybatis 自动映射
mybatis:
  configuration:
    map-underscore-to-camel-case: true
