server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot
    password: 123456
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  #  mybatis.config = mybatis 配置文件名称
  #  mybatis.mapperLocations = mapper xml 文件地址
  #  mybatis.typeAliasesPackage = 实体类包路径
  #  mybatis.typeHandlersPackage = type handlers 处理器包路径
  #  mybatis.check-config-location = 检查 mybatis 配置是否存在，一般命名为 mybatis-config.xml
  #  mybatis.executorType = 执行模式。默认是 SIMPLE
mybatis:
  type-aliases-package: com.example.mybatisannotation.domain
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true


