GET http://localhost:8081/api/all
Accept: */*
Cache-Control: no-cathe

###

GET http://localhost:8081/api/2
Accept: */*
Cache-Control: no-cathe

###
POST http://localhost:8081/api/
Accept: */*
Cache-Control: no-cathe
Content-Type: application/json

{
  "provinceId": 4,
  "cityName": "大连",
  "description": "州际赛城市"
}

###
PUT http://localhost:8081/api/
Accept: */*
Cache-Control: no-cathe
Content-Type: application/json

{
  "id": 4,
  "provinceId": 4,
  "cityName": "榆林",
  "description": "产煤"
}

###
DELETE http://localhost:8081/api/4
Accept: */*
Cache-Control: no-cathe
Content-Type: application/json

###