spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    password: 123456
    username: root
# mybatis配置
mybatis:
  type-aliases-package: com.example.mybatisredis.domain
  mapper-locations: classpath:mapper/*.xml